# application.yml
#mybatis:
#  type-aliases-package: com.example.springboot_messageborad.domain
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123